/** 安全教育 · 学校端 · 产品批注数据 */
window.SAFETY_PROTO_SCHOOL = {
  name: '安全教育 · 学校端',
  goal: '为校管理员提供本校安全宣传与安全提醒的内容发布与运营入口；遵循 Ant Design Pro 后台规范，优先运营效率。',
  structure: 'ProTable 式列表页（搜索/筛选/排序/分页/批量下架/删除/行内 Switch）+ 独立平铺编辑页（新增即发布、编辑保存/重新发布）+ Drawer 详情 + Modal 发布确认 + 右侧产品批注栏。',
  designPrinciples: '①高频操作（置顶/上架/查看/编辑/删除）在列表；②封面/富文本在编辑页；③置顶/上架用 Switch；④正文独立编辑页；⑤详情 Drawer；⑥发布确认 Modal；⑦列表排序；⑧删除二次确认；⑨无草稿态（新增直接发布）；⑩批量下架/删除；⑪默认搜索筛选分页；⑫Ant Design Pro 布局；⑬运营效率优先；⑭分页+服务端扩展。',
  modules: [
    { num:'①', name:'内容类型统计', purpose:'展示宣传/提醒条数，快速感知发布规模。',
      logic:'本校全量（含已发布/已下架）按 content_type 计数；不汇总 PV。',
      interaction:'自动刷新，不可点击。',
      fields:'安全宣传条数、安全提醒条数。',
      data:{ source:'CONTENTS 按 school_id', update:'renderKpi 前端计数', timing:'列表刷新时', sync:'与列表同源', calc:'PUBLICITY/REMINDER count' },
      stateFlow:'随增删改变化。',
      impact:'仅 KPI 展示。',
      exception:'无数据显示 0。',
      scope:'1.0 · KPI 区。',
      permission:'校管理员。',
      metrics:'类型条数占比。' },
    { num:'②', name:'筛选与新增', purpose:'搜索、筛选、新增入口（ProTable 工具栏）。',
      logic:'标题模糊 + 类型 + 状态（已发布/已下架）AND；默认 update_time 倒序；无草稿筛选。',
      interaction:'即时过滤；「新增」进独立编辑页，填完直接「发布」。',
      fields:'filterType、filterStatus、filterKw。',
      data:{ source:'CONTENTS', update:'filtered()', timing:'筛选项变更', sync:'仅视图', calc:'AND 过滤' },
      stateFlow:'不改业务状态。',
      impact:'列表展示范围。',
      exception:'无结果空态。',
      scope:'1.0 · 工具栏。',
      permission:'校管理员。',
      tracking:'safety_filter_change、safety_add_click。' },
    { num:'③', name:'内容列表与详情 Drawer', purpose:'表格浏览；点击标题 Drawer 只读查看（不跳编辑页）。',
      logic:'含已发布/已下架；标题链接触发 Drawer；Drawer 内可进编辑。',
      interaction:'标题 → Drawer；Drawer「编辑」→ 独立编辑页。',
      fields:'列表各列；Drawer 展示 title、meta、content HTML。',
      data:{ source:'filtered()', update:'renderList / openDrawer', timing:'点击标题', sync:'与 CONTENTS 一致', calc:'无' },
      stateFlow:'只读查看。',
      impact:'提升查看效率，减少误进编辑。',
      exception:'记录不存在提示。',
      scope:'1.0 · 表格 + Drawer。',
      permission:'校管理员。',
      tracking:'safety_detail_drawer_view。' },
    { num:'④', name:'列表高频操作', purpose:'行内 Switch（置顶/上架）、编辑、删除。',
      logic:'置顶 Switch 仅已发布（已上架）可用；上架 Switch 与 status 同源：开=PUBLISHED、关=OFFLINE；发布同步上架（见批注⑩），下架同步关 Switch。已下架恢复可见性仅开上架 Switch；改内容并同步上架走编辑页「重新发布」。',
      interaction:'Switch 即时生效；编辑进独立页；无列表「重新发布」按钮（与上架 Switch 合并）。',
      fields:'is_top、status、publish_time、update_time。',
      data:{ source:'行内操作', update:'publishItem / offlineItem', timing:'Switch/按钮点击', sync:'status 与上架 Switch 始终一致', calc:'发布/上架开 → publishItem' },
      stateFlow:'OFFLINE→PUBLISHED（publishItem）；PUBLISHED→OFFLINE（offlineItem）。',
      impact:'家长端可见性、置顶排序。',
      exception:'删除/批量删除均需 confirm；已发布项保存后 Switch 已为开，再点会下架（见批注⑩）。',
      scope:'1.0 · 列表行 + Switch 列。',
      permission:'校管理员。',
      metrics:'置顶率、下架率。' },
    { num:'⑤', name:'独立编辑页', purpose:'低频配置：类型、标题、封面、富文本；新增仅「发布」，编辑态「保存」⑪与「重新发布」⑦二选一。',
      logic:'新增模式无保存，填完「发布」（⑦）。编辑模式底部两按钮：「保存」⑪只改内容；「重新发布」⑦改内容+同步上架+刷新发布时间；二者区别见⑪ logic 对比表。',
      interaction:'平铺独立页；新增「取消+发布」；编辑「取消+保存⑪+重新发布⑦」；取消回列表。',
      fields:'content_type、title、cover_url、content。',
      data:{ source:'编辑表单', update:'保存→mergeFormData；发布/重新发布→publishWithForm', timing:'点击按钮', sync:'saveData', calc:'见⑪⑦' },
      stateFlow:'新建仅发布→PUBLISHED。编辑保存/重新发布分支见⑪⑩。',
      impact:'内容与可见性可在编辑页分步处理。',
      exception:'新增不展示保存按钮。',
      scope:'1.0 · 独立 Form 页。',
      permission:'校管理员。',
      tracking:'safety_form_save、safety_form_publish。' },
    { num:'⑥', name:'富文本正文', purpose:'正文编辑（独立页低频重操作）。',
      logic:'基础格式+插图；正式接 WangEditor；XSS 过滤。',
      interaction:'工具栏编辑。',
      fields:'content（HTML）。',
      data:{ source:'rteBody', update:'随表单提交', timing:'保存/发布', sync:'家长端详情', calc:'无' },
      stateFlow:'随内容记录。',
      impact:'详情正文。',
      exception:'发布时空正文拦截。',
      scope:'1.0 · 编辑页。',
      extension:'标准富文本组件。' },
    { num:'⑦', name:'发布确认 Modal', purpose:'新增发布 / 编辑「重新发布」前二次确认；与「保存」⑪分工不同（见对比表）。',
      logic:'无草稿；确认后 createPublishedItem（新增）或 publishWithForm→publishItem（重新发布）：合并表单 + status=PUBLISHED + 同步上架 Switch 开 + 刷新 publish_time，pv_count 不变。【保存 vs 重新发布】保存⑪：只 mergeFormData，不改 status/publish_time，已下架仍不可见，无 Modal。重新发布⑦：mergeFormData + publishItem，必 PUBLISHED，刷新 publish_time，已下架一并上线，有 Modal。已发布时二者家长均见新正文，但仅重新发布刷新发布时间。',
      interaction:'Modal 确认/取消；编辑页「发布/重新发布」使用；「保存」不走本 Modal。列表上架 Switch 即时生效，不走本 Modal。',
      fields:'confirmTitle、confirmDesc。',
      data:{ source:'表单或列表项', update:'publishWithForm→publishItem', timing:'确认后', sync:'他端可读', calc:'统一 publishItem' },
      stateFlow:'OFFLINE → PUBLISHED（重新发布保留 PV）。',
      impact:'家长端可见。',
      exception:'失败保留编辑态；与保存⑪区别见 logic 对比表。',
      scope:'1.0 · Modal。',
      permission:'校管理员。',
      tracking:'safety_publish_confirm。',
      metrics:'发布转化率。' },
    { num:'⑧', name:'PV 统计（浏览量）', purpose:'列表逐条展示 pv_count；学校端只读；唯一写入来自家长端详情访问。',
      logic:'触发：家长端进入 PUBLISHED 详情 +1。不计：列表曝光、学校/平台 Drawer、下架期间新增。初始发布=0；下架/删稿保留或随删；重新发布不重置。1.0 不去重；正式 24h 同账号同内容计 1 次。',
      interaction:'学校端只读列+排序；Drawer 展示当前值；不可编辑清零。',
      fields:'pv_count（school_safety_content）。',
      data:{
        source:'school_safety_content.pv_count',
        update:'仅家长端 POST view 或原型 localStorage +1',
        timing:'家长详情页加载成功时',
        sync:'DB 原子 +1 → 学校/平台/家长读同一字段',
        calc:'pv_count += 1；失败不阻塞阅读'
      },
      stateFlow:'OFFLINE 不计新增；PUBLISHED 可累加；OFFLINE 冻结计数。',
      impact:'学校列表浏览量列、平台监管列、家长详情底部阅读量。',
      exception:'接口失败展示旧值；无权限/下架不计；并发用原子更新。',
      scope:'1.0 · 列表列+排序+Drawer；正式接口见 PRD 第九章。',
      permission:'学校/平台只读；写入仅家长端。',
      metrics:'单篇 PV、内容点击率（列表点击/ PV 分开）。',
      tracking:'parent_safety_pv（计数成功）；parent_safety_detail_view（曝光）。',
      extension:'UV、view_log 明细、防刷、导出阅读报表。' },
    { num:'⑨', name:'批量操作', purpose:'批量下架/删除，提升运营效率。',
      logic:'勾选多行后显示 batch-bar；批量删除/下架 confirm；无批量发布（新增走编辑页发布并同步上架；下架项用上架 Switch 或编辑重新发布恢复）。',
      interaction:'全选/行选 → 批量按钮；「取消选择」清空。',
      fields:'selectedIds。',
      data:{ source:'勾选集合', update:'offlineItem 或 filter 删除', timing:'批量按钮点击', sync:'同单条', calc:'无' },
      stateFlow:'同单条批量版。',
      impact:'多条内容可见性。',
      exception:'空选择禁用按钮；删除 confirm。',
      scope:'1.0 · 批量工具栏；正式可扩展导出等。',
      permission:'校管理员。',
      extension:'批量置顶、批量导出。' },
    { num:'⑩', name:'发布同步上架（状态与流转）', purpose:'明确发布、上架、下架为同一可见性状态的不同入口；并说明「编辑保存后再上架」与「重新发布」的差异。',
      logic:'【核心】发布同步上架：发布/重新发布（Modal⑦）或上架 Switch 开 → status=PUBLISHED、Switch 开、家长可见。Switch 关/批量下架 → OFFLINE、Switch 关。【保存】规则见批注⑪；保存后再开 Switch 或重新发布的组合路径如下。',
      interaction:'路径 A（改文+推送，需确认）：编辑→重新发布→Modal⑦→PUBLISHED。路径 B（改文+稍后上线）：编辑→保存→回列表→开 Switch（无 Modal，publish_time 以开 Switch 为准）。路径 C（已发布微调）：编辑→保存即可，勿动 Switch。暂隐：Switch 关。',
      fields:'status（PUBLISHED=已发布且已上架 / OFFLINE=已下架）、publish_time、update_time、pv_count。',
      data:{ source:'publishItem / offlineItem / mergeFormData', update:'保存只 mergeFormData；Switch开/发布走 publishItem；Switch关走 offlineItem', timing:'保存=编辑页；Switch=列表即时', sync:'status 与 Switch 单一数据源', calc:'publishItem 刷新 publish_time；offlineItem 不改 publish_time；保存不改 publish_time' },
      stateFlow:'【已下架】编辑保存→OFFLINE（内容已更新）。→ 开 Switch→PUBLISHED（publish_time=Switch时刻）。→ 或 编辑重新发布 Modal⑦→PUBLISHED（publish_time=确认时刻）。两条路径 publish_time 锚点不同，正文均为最新保存内容。【已发布】编辑保存→PUBLISHED（publish_time不变，家长即时见新文）。→ 再点 Switch→误下架 OFFLINE。【新建】发布 Modal⑦→PUBLISHED（pv=0）。→ 平台强制下架→OFFLINE→学校 Switch开或重新发布恢复。',
      impact:'运营可选「先改后上」或「改完即推」；列表排序按 publish_time，故保存+Switch 与重新发布的发布时间可能不同。',
      exception:'无草稿态；置顶仅 PUBLISHED；列表无「重新发布」按钮；正式可考虑保存后对 OFFLINE 项提示「是否同步上架」。',
      scope:'1.0 · 全模块状态机；与批注④⑤⑦联动。',
      permission:'校管理员。',
      metrics:'保存后 Switch 上架占比、重新发布占比。',
      tracking:'safety_publish_confirm、safety_shelf_toggle、safety_offline_batch、safety_form_save。' },
    { num:'⑪', name:'编辑页 · 保存', purpose:'编辑已有内容时，仅持久化字段变更，不触发发布/上架；与「重新发布」⑦ 分工见下方对比。',
      logic:'【操作】collectForm + mergeFormData → 写 title/content/type/cover、update_time；不调 publishItem。【不改】status、publish_time、is_top、pv_count。【保存 vs 重新发布 对比】①意图：保存=只改稿入库；重新发布=改稿并对外推送/恢复可见。②确认：保存无 Modal；重新发布 Modal⑦。③status：保存不变；重新发布→PUBLISHED（Switch 同步开）。④publish_time：保存不变；重新发布刷新为确认时刻（影响列表排序与家长端展示日期）。⑤已发布时：保存后家长立即见新正文、发布时间不变；重新发布后家长见新正文、发布时间更新。⑥已下架时：保存后仍不可见；重新发布后立即可见。⑦pv_count：二者均不重置。⑧选用：已上线静默修错→保存；要刷新发布时间或下架改完一并上线→重新发布；下架仅改稿稍后再上→保存+列表 Switch（⑩路径 B）。',
      interaction:'校验标题+正文 → mergeFormData → saveData → Toast → 回列表。与「重新发布」同一编辑页二选一，不可同时触发。',
      fields:'title、content、content_type、cover_url、update_time（写入）；status、publish_time（不写入）。',
      data:{ source:'编辑表单 #fmTitle #fmType #rteBody', update:'mergeFormData(item, data)', timing:'点击「保存」', sync:'localStorage/API 即时持久化', calc:'无 publish_time 变更' },
      stateFlow:'PUBLISHED + 保存 → PUBLISHED（publish_time 不变，正文更新，家长可见）。OFFLINE + 保存 → OFFLINE（正文更新，家长不可见）→ 可选：列表 Switch 开 或 重新发布。保存 ≠ 发布；与重新发布互斥于同一时刻（用户二选一按钮）。',
      impact:'支持「先改稿、稍后再推」；已发布内容可静默修错而不刷新发布时间、不打扰家长排序感知。',
      exception:'仅编辑态展示保存按钮（新增无）；校验失败不写入；已发布保存后勿再点上架 Switch（见⑩）；与重新发布区别见 logic 对比表。',
      scope:'1.0 · 编辑页底部「保存」按钮（btnSaveEdit）；仅编辑态。',
      permission:'校管理员。',
      metrics:'保存次数、保存后 24h 内重新发布/上架占比。',
      tracking:'safety_form_save。' }
  ],
  extension:'服务端分页排序；定时发布；定向推送；阅读报表；消息通知。'
};
