/** 安全教育 · 学校端 · 产品批注数据 */
window.SAFETY_PROTO_SCHOOL = {
  name: '安全教育 · 学校端',
  goal: '为校管理员提供本校安全宣传与安全提醒的内容发布与运营入口；遵循 Ant Design Pro 后台规范，优先运营效率。',
  structure: 'ProTable 式列表页（搜索/筛选/排序/分页/批量下架/删除/行内 Switch）+ 独立平铺编辑页（新增即发布、编辑保存/重新发布）+ Drawer 详情 + Modal 发布确认 + 右侧产品批注栏。',
  designPrinciples: '①高频操作（置顶/上架/查看/编辑/删除）在列表；②封面/富文本在编辑页；③置顶/上架用 Switch；④正文独立编辑页；⑤详情 Drawer；⑥发布确认 Modal；⑦列表排序；⑧删除二次确认；⑨无草稿态（新增直接发布）；⑩批量下架/删除；⑪默认搜索筛选分页；⑫Ant Design Pro 布局；⑬运营效率优先；⑭分页+服务端扩展。',
  modules: [
    { num:'①', name:'内容类型统计', purpose:'展示宣传/提醒条数，快速感知发布规模。',
      logic:'本校全量（含已发布/已下架）按 content_type 计数；不汇总 PV。',
      interaction:'自动刷新，不可点击。',
      fields:'安全宣传条数、安全提醒条数。',
      data:{ source:'CONTENTS 按 school_id', update:'renderKpi 前端计数', timing:'列表刷新时', sync:'与列表同源', calc:'PUBLICITY/REMINDER count' },
      stateFlow:'随增删改变化。',
      impact:'仅 KPI 展示。',
      exception:'无数据显示 0。',
      scope:'1.0 · KPI 区。',
      permission:'校管理员。',
      metrics:'类型条数占比。' },
    { num:'②', name:'筛选与新增', purpose:'搜索、筛选、新增入口（ProTable 工具栏）。',
      logic:'标题模糊 + 类型 + 状态（已发布/已下架）AND；默认 update_time 倒序；无草稿筛选。',
      interaction:'即时过滤；「新增」进独立编辑页，填完直接「发布」。',
      fields:'filterType、filterStatus、filterKw。',
      data:{ source:'CONTENTS', update:'filtered()', timing:'筛选项变更', sync:'仅视图', calc:'AND 过滤' },
      stateFlow:'不改业务状态。',
      impact:'列表展示范围。',
      exception:'无结果空态。',
      scope:'1.0 · 工具栏。',
      permission:'校管理员。',
      tracking:'safety_filter_change、safety_add_click。' },
    { num:'③', name:'内容列表与详情 Drawer', purpose:'表格浏览；点击标题 Drawer 只读查看（不跳编辑页）。',
      logic:'含已发布/已下架；标题链接触发 Drawer；Drawer 内可进编辑。',
      interaction:'标题 → Drawer；Drawer「编辑」→ 独立编辑页。',
      fields:'列表各列；Drawer 展示 title、meta、content HTML。',
      data:{ source:'filtered()', update:'renderList / openDrawer', timing:'点击标题', sync:'与 CONTENTS 一致', calc:'无' },
      stateFlow:'只读查看。',
      impact:'提升查看效率，减少误进编辑。',
      exception:'记录不存在提示。',
      scope:'1.0 · 表格 + Drawer。',
      permission:'校管理员。',
      tracking:'safety_detail_drawer_view。' },
    { num:'④', name:'列表高频操作', purpose:'行内 Switch（置顶/上架）、编辑、重新发布、删除。',
      logic:'置顶 Switch 仅已发布可用；上架 Switch 开/关走 publishItem/offlineItem；已下架可「重新发布」或开 Switch；不想展示家长端用下架或删除；无草稿。',
      interaction:'Switch 即时生效；编辑进独立页；已下架「重新发布」走 Modal⑦。',
      fields:'is_top、status、publish_time、update_time。',
      data:{ source:'行内操作', update:'publishItem / offlineItem', timing:'Switch/按钮点击', sync:'家长端可见性随 PUBLISHED/OFFLINE', calc:'发布刷新 publish_time' },
      stateFlow:'OFFLINE→PUBLISHED（publishItem）；PUBLISHED→OFFLINE（offlineItem）。',
      impact:'家长端可见性、置顶排序。',
      exception:'删除/批量删除均需 confirm。',
      scope:'1.0 · 列表行 + Switch 列。',
      permission:'校管理员。',
      metrics:'置顶率、下架率。' },
    { num:'⑤', name:'独立编辑页', purpose:'低频配置：类型、标题、封面、富文本；新增即发布，编辑可保存或重新发布。',
      logic:'新增：仅「发布」（标题+正文必填，确认后直接 PUBLISHED）；编辑：「保存」仅改内容不改 publish_time；「重新发布」刷新 publish_time 并上架；暂不上架用列表下架 Switch 或删除。',
      interaction:'平铺独立页；新增「取消+发布」；编辑「取消+保存+重新发布」；取消回列表。',
      fields:'content_type、title、cover_url、content。',
      data:{ source:'编辑表单', update:'mergeFormData / publishWithForm / createPublishedItem', timing:'点击保存/发布', sync:'saveData', calc:'发布 publishItem' },
      stateFlow:'新建→PUBLISHED；编辑保存不改状态；重新发布→PUBLISHED+新 publish_time。',
      impact:'家长端内容展示。',
      exception:'校验失败提示。',
      scope:'1.0 · 独立 Form 页；置顶在列表 Switch。',
      permission:'校管理员。',
      tracking:'safety_form_save、safety_form_publish。' },
    { num:'⑥', name:'富文本正文', purpose:'正文编辑（独立页低频重操作）。',
      logic:'基础格式+插图；正式接 WangEditor；XSS 过滤。',
      interaction:'工具栏编辑。',
      fields:'content（HTML）。',
      data:{ source:'rteBody', update:'随表单提交', timing:'保存/发布', sync:'家长端详情', calc:'无' },
      stateFlow:'随内容记录。',
      impact:'详情正文。',
      exception:'发布时空正文拦截。',
      scope:'1.0 · 编辑页。',
      extension:'标准富文本组件。' },
    { num:'⑦', name:'发布确认 Modal', purpose:'新增发布 / 编辑重新发布 / 列表重新发布前二次确认。',
      logic:'无草稿；新增确认后直接 createPublishedItem；编辑/下架项重新发布走 publishItem（刷新 publish_time，PV 不变）。',
      interaction:'Modal 确认/取消；编辑页发布、列表重新发布共用（上架 Switch 开即时生效无 Modal）。',
      fields:'confirmTitle、confirmDesc。',
      data:{ source:'表单或列表项', update:'publishWithForm / doPublish→publishItem', timing:'确认后', sync:'他端可读', calc:'统一 publishItem' },
      stateFlow:'OFFLINE → PUBLISHED（重新发布保留 PV）。',
      impact:'家长端可见。',
      exception:'失败保留编辑态。',
      scope:'1.0 · Modal。',
      permission:'校管理员。',
      tracking:'safety_publish_confirm。',
      metrics:'发布转化率。' },
    { num:'⑧', name:'PV 统计（浏览量）', purpose:'列表逐条展示 pv_count；学校端只读；唯一写入来自家长端详情访问。',
      logic:'触发：家长端进入 PUBLISHED 详情 +1。不计：列表曝光、学校/平台 Drawer、下架期间新增。初始发布=0；下架/删稿保留或随删；重新发布不重置。1.0 不去重；正式 24h 同账号同内容计 1 次。',
      interaction:'学校端只读列+排序；Drawer 展示当前值；不可编辑清零。',
      fields:'pv_count（school_safety_content）。',
      data:{
        source:'school_safety_content.pv_count',
        update:'仅家长端 POST view 或原型 localStorage +1',
        timing:'家长详情页加载成功时',
        sync:'DB 原子 +1 → 学校/平台/家长读同一字段',
        calc:'pv_count += 1；失败不阻塞阅读'
      },
      stateFlow:'OFFLINE 不计新增；PUBLISHED 可累加；OFFLINE 冻结计数。',
      impact:'学校列表浏览量列、平台监管列、家长详情底部阅读量。',
      exception:'接口失败展示旧值；无权限/下架不计；并发用原子更新。',
      scope:'1.0 · 列表列+排序+Drawer；正式接口见 PRD 第九章。',
      permission:'学校/平台只读；写入仅家长端。',
      metrics:'单篇 PV、内容点击率（列表点击/ PV 分开）。',
      tracking:'parent_safety_pv（计数成功）；parent_safety_detail_view（曝光）。',
      extension:'UV、view_log 明细、防刷、导出阅读报表。' },
    { num:'⑨', name:'批量操作', purpose:'批量下架/删除，提升运营效率。',
      logic:'勾选多行后显示 batch-bar；批量删除/下架 confirm；无批量发布（新增即发布、下架项用 Switch 或重新发布）。',
      interaction:'全选/行选 → 批量按钮；「取消选择」清空。',
      fields:'selectedIds。',
      data:{ source:'勾选集合', update:'offlineItem 或 filter 删除', timing:'批量按钮点击', sync:'同单条', calc:'无' },
      stateFlow:'同单条批量版。',
      impact:'多条内容可见性。',
      exception:'空选择禁用按钮；删除 confirm。',
      scope:'1.0 · 批量工具栏；正式可扩展导出等。',
      permission:'校管理员。',
      extension:'批量置顶、批量导出。' }
  ],
  extension:'服务端分页排序；定时发布；定向推送；阅读报表；消息通知。'
};
